### ISSUE TITLE
Morning Session Pair to Pair Code Review

### ISSUE THREAD

**Issue by toyman640** [Mahamadou-Nouridine/My-Portfolio#9]
- Please use the appropriate tag selector referenced in the lesson
- Add alt messages to image tags at lines 60, 65, 70, 85
- Please make sure the menu bar closes when you click on any menu item
- Please ensure scroll is disabled when the hamburger menu is being displayed
- Fix the lighthouse error

**Comment by Mahamadou-Nouridine** [comment]
Issue fixed, thank you for the review
